### ISSUE TITLE
Decompilation failed

### ISSUE THREAD

**Issue by CONIGUERO** [AITYunivers/NebulaFD#14]
Used JR's as a test.

This happens when dumping frames:

```
[23:38:02] ERROR:
Index was outside the bounds of the array.
   at Nebula.Core.Utilities.ImageTranslatorCPU.Normal24BitMaskedToRGBA(Image img) in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Utilities\ImageTranslatorCPU.cs:line 56
   at Nebula.Core.Data.Chunks.BankChunks.Images.Image.GetData() in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Images\Image.cs:line 81
   at Nebula.Core.Data.Chunks.BankChunks.Images.Image.GetBitmap() in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Images\Image.cs:line 174
   at Nebula.Core.Utilities.Utilities.MakeFrameImg(Frame frm, Int32 layer, Boolean showHiddenObjects, Boolean
useFrameSize) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Utilities\Utilities.cs:line 193
   at Nebula.Tools.GameDumper.FrameDump.<Execute>b__5_0(ProgressContext ctx) in
D:\a\NebulaFD\NebulaFD\Nebula.Tools\InfoDump\FrameDump.cs:line 43
   at Spectre.Console.Progress.<>c__DisplayClass29_0.<Start>b__0(ProgressContext ctx) in
/_/src/Spectre.Console/Live/Progress/Progress.cs:line 70
   at Spectre.Console.Progress.<>c__DisplayClass31_0.<<StartAsync>b__0>d.MoveNext() in
/_/src/Spectre.Console/Live/Progress/Progress.cs:line 103
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext() in
/_/src/Spectre.Console/Live/Progress/Progress.cs:line 138
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in
/_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 121
   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 101
   at Spectre.Console.Progress.Start(Action`1 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 74
   at Nebula.Tools.GameDumper.FrameDump.Execute() in D:\a\NebulaFD\NebulaFD\Nebula.Tools\InfoDump\FrameDump.cs:line 20
   at Nebula.Program.SelectTool() in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 232
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nebula.Core.Utilities.ImageTranslatorCPU.Normal24BitMaskedToRGBA(Image img) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Utilities\ImageTranslatorCPU.cs:line 56
   at Nebula.Core.Data.Chunks.BankChunks.Images.Image.GetData() in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Images\Image.cs:line 81
   at Nebula.Core.Data.Chunks.BankChunks.Images.Image.GetBitmap() in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Images\Image.cs:line 174
   at Nebula.Core.Utilities.Utilities.MakeFrameImg(Frame frm, Int32 layer, Boolean showHiddenObjects, Boolean useFrameSize) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Utilities\Utilities.cs:line 193
   at Nebula.Tools.GameDumper.FrameDump.<Execute>b__5_0(ProgressContext ctx) in D:\a\NebulaFD\NebulaFD\Nebula.Tools\InfoDump\FrameDump.cs:line 43
   at Spectre.Console.Progress.<>c__DisplayClass29_0.<Start>b__0(ProgressContext ctx) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 70
   at Spectre.Console.Progress.<>c__DisplayClass31_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 103
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 138
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 121
   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 101
   at Spectre.Console.Progress.Start(Action`1 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 74
   at Nebula.Tools.GameDumper.FrameDump.Execute() in D:\a\NebulaFD\NebulaFD\Nebula.Tools\InfoDump\FrameDump.cs:line 20
   at Nebula.Program.SelectTool() in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 232
   at Nebula.Program.SpectreMain() in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 41
   at Nebula.Program.Main(String[] args) in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 33
   at Nebula.Program.<Main>(String[] args)
```

**Comment by AITYunivers** [comment]
Frame Dumper removed in f8ce2bb
