### ISSUE TITLE
APK Decompilation Failed

### ISSUE THREAD

**Issue by DieGGPro** [AITYunivers/NebulaFD#17]
I am a MFA collector and I am trying to get the MFA of a Clickteam APK game, but every time I try to decompile it (Yes, I have selected the APK option), Nebula manages to just decompile some frames but later it gives out this error:

ERROR:
The given key '13' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Nebula.Core.Data.Chunks.BankChunks.Shaders.DX9ShaderBank.get_Item(Int32 key) in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Shaders\DX9ShaderBank.cs:line 55
   at Nebula.Core.Data.Chunks.BankChunks.Shaders.ShaderBank.get_Item(Int32 key) in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Shaders\ShaderBank.cs:line 67
   at Nebula.Core.Data.Chunks.FrameChunks.FrameLayerEffect.ReadCCN(ByteReader reader, Object[] extraInfo) in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\FrameChunks\FrameLayerEffect.cs:line 36
   at Nebula.Core.Data.Chunks.FrameChunks.FrameLayerEffects.ReadCCN(ByteReader reader, Object[] extraInfo) in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\FrameChunks\FrameLayerEffects.cs:line 20
   at Nebula.Core.Data.Chunks.FrameChunks.Frame.ReadCCN(ByteReader reader, Object[] extraInfo) in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\FrameChunks\Frame.cs:line 68
   at Nebula.Core.Data.PackageReaders.CCNPackageData.Read(ByteReader reader) in
D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\PackageReaders\CCNPackageData.cs:line 50
   at Nebula.Program.ReadPackage() in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 158
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '13' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Nebula.Core.Data.Chunks.BankChunks.Shaders.DX9ShaderBank.get_Item(Int32 key) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Shaders\DX9ShaderBank.cs:line 55
   at Nebula.Core.Data.Chunks.BankChunks.Shaders.ShaderBank.get_Item(Int32 key) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\BankChunks\Shaders\ShaderBank.cs:line 67
   at Nebula.Core.Data.Chunks.FrameChunks.FrameLayerEffect.ReadCCN(ByteReader reader, Object[] extraInfo) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\FrameChunks\FrameLayerEffect.cs:line 36
   at Nebula.Core.Data.Chunks.FrameChunks.FrameLayerEffects.ReadCCN(ByteReader reader, Object[] extraInfo) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\FrameChunks\FrameLayerEffects.cs:line 20
   at Nebula.Core.Data.Chunks.FrameChunks.Frame.ReadCCN(ByteReader reader, Object[] extraInfo) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\Chunks\FrameChunks\Frame.cs:line 68
   at Nebula.Core.Data.PackageReaders.CCNPackageData.Read(ByteReader reader) in D:\a\NebulaFD\NebulaFD\Nebula.Core\Data\PackageReaders\CCNPackageData.cs:line 50
   at Nebula.Program.ReadPackage() in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 158
   at Nebula.Program.SpectreMain() in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 40
   at Nebula.Program.Main(String[] args) in D:\a\NebulaFD\NebulaFD\Nebula.CLI\Program.cs:line 33
   at Nebula.Program.<Main>(String[] args)

**Comment by Jay9999IQ** [comment]
he will not fix the problem because they are so garbage at making decompilers
